### ISSUE TITLE
npm install -g Moneyd not working..

### ISSUE THREAD

**Issue by Rospel0Funk** [interledgerjs/moneyd#119]
I'm working on a Mac running the most recent operating system, just updated, at first I was having permission problems but I fixed them all, now its gone from giving me 700 lines of code to tell me I have a problem to 6k lines....... and nothing is specific but it always outputs this at the beginning, (the shorter pic) and the bigger one at the end.

**Comment by Rospel0Funk** [comment]
sorry in advance it's not letting me upload any pictures of anything...... so here is the code that its always showing before  

prebuild-install WARN install No prebuilt binaries found (target=12.13.0 runtime=node arch=x64 platform=darwin)

**Comment by Rospel0Funk** [comment]
[2019-10-24T06_07_27_681Z-debug.log](https://github.com/interledgerjs/moneyd/files/3766028/2019-10-24T06_07_27_681Z-debug.log)
<img width="565" alt="Screen Shot 2019-10-23 at 11 25 33 PM" src="https://user-images.githubusercontent.com/25734527/67459476-880b3180-f5ed-11e9-9344-89fbe0af60ed.png">
<img width="568" alt="Screen Shot 2019-10-23 at 11 25 55 PM" src="https://user-images.githubusercontent.com/25734527/67459478-880b3180-f5ed-11e9-8e7c-a99ade217263.png">

**Comment by kmacthecoder** [comment]
i am also getting this problem

```

**Comment by kmacthecoder** [comment]
@Rospel0Funk  i downgraded my node version from v12.13.0 to v8.9.4 and the `moneyd` module installs fine now 

must have been some incompatibility issues with the newest node version that messed up the `moneyd` installation

**Comment by LoisRP** [comment]
I have been having this problem too. What is the maximum version number of node that is likely to work?

**Comment by Rospel0Funk** [comment]
i was told that they stopped updating this one, and given another one to download, this is just one platform to access the inter ledger, hasn't really been clear to me, and i havn't been active though, just good
